version: '3'
services:
  app:
    container_name: cl-node-app
    image: cartilla_libre:latest
    build:
      context: .
    depends_on:
      - mongo_db
    env_file: .env
    command: npm run ${ENV}
    ports:
      - '4000:4000'
    volumes:
      - .:/cartillalibre
      - /cartillalibre/node_modules
    links:
      - mongo_db

  mongo_db:
    container_name: mongo-db
    image: mongo
    expose:
      - '27017'
    volumes:
    - mongodata:/data/db

volumes:
  mongodata:
